workout_app/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

# Define URL patterns for the users app
urlpatterns = [
    path('', views.index, name="index"),  # Map the root URL to the index view
    path('login', views.login_view, name="login"),  # Map the /login URL to the login_view
    path('logout', views.logout_view, name="logout"),  # Map the /logout URL to the logout_view
    path('register/', views.register_view, name='register'),  # Map the /register URL to the register_view
]

# Add URL patterns for serving media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workout_app/workout_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Include URLs from the 'users' app
    path("", include('users.urls')),
    
    # Admin panel URL
    path("admin/", admin.site.urls),
    
    # Include URLs from the 'workout_logs' app
    path("workout_logs/", include('workout_logs.urls')),
    
    # Include URLs from the 'payments' app
    path('payments/', include('payments.urls')),
]

workout_app/workout_logs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # URL for the home/index page
    path('', views.index, name='index'),

    # URL for the workout history page with filtering options
    path('history/', views.history, name='history'),

    # URL for adding a new workout
    path('add_workout/', views.add_workout, name='add_workout'),

    # URL for the user profile page
    path('profile/', views.profile, name='profile'),

    # URL for deleting a specific workout with dynamic workout_id
    path('delete_workout/<int:workout_id>/', views.delete_workout, name='delete_workout'),

    # URL for editing a specific workout with dynamic workout_id
    path('edit_workout/<int:workout_id>/', views.edit_workout, name='edit_workout'),

    # URL for the Frequently Asked Questions (FAQ) page
    path('faq/', views.faq, name='faq'),
]

workout_app/workout_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Model for types of exercises
class Exercise(models.Model):
    # Name of the exercise
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

# Model for Cardio exercises
class Cardio(models.Model):
    # User associated with the exercise
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    # Type of exercise (linked to Exercise model)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE, default=1)

    # Date and time when the exercise was created
    created_at = models.DateTimeField(default=timezone.now)

    # Duration of the exercise
    duration = models.DurationField(null=True, default=0)

    # Distance covered during the exercise
    distance = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    # Additional comments for the exercise
    comment = models.TextField(default='')

    def __str__(self):
        # String representation of the Cardio exercise
        return f"{self.user.username}'s {self.exercise.name}"

workout_app/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile

class RegisterForm(UserCreationForm):
    """
    Form for user registration, extending the built-in UserCreationForm.
    """
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserProfileForm(forms.ModelForm):
    """
    Form for additional user profile information.
    """
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'profile_picture']

workout_app/workout_logs/forms.py
from django import forms
from .models import Cardio

# Form for capturing Cardio exercise details
class CardioForm(forms.ModelForm):
    class Meta:
        # Associate the form with the Cardio model
        model = Cardio

        # Specify the fields to be included in the form
        fields = ['exercise', 'created_at', 'duration', 'distance', 'comment']

workout_app/workout_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from .models import Exercise, Cardio
from .forms import CardioForm
from users.models import UserProfile
from users.forms import UserProfileForm

from datetime import datetime, timedelta
from decimal import Decimal

from PIL import Image

# View to display the latest 3 exercises for the logged-in user
@login_required
def index(request):
    user = request.user
    latest_exercises = Cardio.objects.order_by('-created_at').filter(user=user)[:3]
    return render(request, "workout_logs/index.html", {'latest_exercises': latest_exercises})

# View to display workout history with various filtering options
@login_required
def history(request):
    workouts = Cardio.objects.order_by('-created_at').filter(user=request.user)

    exercise_name = request.GET.get('exercise_name')
    if exercise_name:
        workouts = workouts.filter(exercise__name=exercise_name)

    exercise_info = request.GET.get('exercise_info')
    if exercise_info:
        workouts = workouts.filter(
            Q(exercise__name__icontains=exercise_info)
            | Q(comment__icontains=exercise_info)
        )

    distance_start = request.GET.get('distance_start')
    distance_end = request.GET.get('distance_end')
    if distance_start and distance_end:
        workouts = workouts.filter(distance__gte=distance_start, distance__lte=distance_end)

    date_start = request.GET.get('date_start')
    date_end = request.GET.get('date_end')
    if date_start and date_end:
        date_start = datetime.strptime(date_start, '%Y-%m-%d').date()
        date_end = datetime.strptime(date_end, '%Y-%m-%d').date()
        workouts = workouts.filter(created_at__date__range=[date_start, date_end])

    duration_start = request.GET.get('duration_start')
    duration_end = request.GET.get('duration_end')
    if duration_start and duration_end:
        duration_start = timedelta(minutes=int(duration_start))
        duration_end = timedelta(minutes=int(duration_end))
        workouts = workouts.filter(duration__gte=duration_start, duration__lte=duration_end)

    exercises = Exercise.objects.all()

    paginator = Paginator(workouts, 8)  # Show 8 workouts per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'exercise_name': exercise_name,
        'exercise_info': exercise_info,
        'distance_start': distance_start,
        'distance_end': distance_end,
        'date_start': request.GET.get('date_start'),
        'date_end': request.GET.get('date_end'),
        'duration_start': duration_start,
        'duration_end': duration_end,
        'exercises': exercises,
    }
    return render(request, "workout_logs/history.html", context)

# View to add a new workout
@login_required
def add_workout(request):
    if request.method == 'POST':
        # Extract workout details from the form and create a new Cardio instance
        exercise_id = request.POST.get('exercise')
        exercise = Exercise.objects.get(id=exercise_id)
        duration_minutes = int(request.POST.get('duration'))
        duration = timedelta(minutes=duration_minutes)
        distance = Decimal(request.POST.get('distance'))
        comment = request.POST.get('comment')
        created_at_str = request.POST.get('created_at')
        created_at = datetime.strptime(created_at_str, '%Y-%m-%dT%H:%M')
        workout = Cardio.objects.create(
            user=request.user,
            exercise=exercise,
            duration=duration,
            distance=distance,
            comment=comment,
            created_at=created_at
        )
        messages.success(request, f'{exercise} {distance}km ({duration})')

    exercises = Exercise.objects.all()

    context = {
        'exercises': exercises,
    }
    return render(request, "workout_logs/add_workout.html", context)

# View to delete a workout
@login_required
def delete_workout(request, workout_id):
    workout = get_object_or_404(Cardio, id=workout_id)

    # Check if the logged-in user is the owner of the workout before deleting
    if request.user == workout.user:
        workout.delete()
        return redirect('index')
    else:
        return HttpResponse('Permission Denied', status=403)

# View to edit a workout
@login_required
def edit_workout(request, workout_id):
    workout = get_object_or_404(Cardio, id=workout_id, user=request.user)

    if request.method == 'POST':
        form = CardioForm(request.POST, instance=workout)
        if form.is_valid():
            form.save()

            # Update the duration in minutes based on the form data
            duration_minutes = int(request.POST.get('duration'))
            workout.duration = timedelta(minutes=duration_minutes)
            workout.save()

            return redirect('history')  # Redirect to the history page after editing
    else:
        form = CardioForm(instance=workout)
        duration_minutes = int(workout.duration.total_seconds() // 60)

    exercises = Exercise.objects.all()

    context = {
        'form': form,
        'current_workout': workout,
        'exercises': exercises,
        'duration_minutes': duration_minutes,
    }
    return render(request, 'workout_logs/edit_workout.html', context)

# View to display and update user profile information
@login_required
def profile(request):
    user = request.user
    try:
        user_profile = UserProfile.objects.get(user=user)
    except UserProfile.DoesNotExist:
        user_profile = None

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            return redirect('profile')
    else:
        form = UserProfileForm(instance=user_profile)

    context = {
        'form': form,
        'user_profile': user_profile,
    }
    return render(request, "workout_logs/profile.html", context)

# View to display FAQ page
def faq(request):
    return render(request, "workout_logs/faq.html")

workout_app/workout_logs/templates/workout_logs/add_workout.html
{% extends "workout_logs/layout.html" %} {% block content %}

<div class="training-page container">
  <!-- Page heading for adding a workout -->
  <h1>Dodaj trening</h1>

  <!-- Display success messages if any -->
  {% if messages %}
  <div
    id="toast-container"
    class="position-fixed top-0 end-0 p-3"
    style="z-index: 9999"
  >
    {% for message in messages %}
    <div
      class="toast"
      role="alert"
      aria-live="assertive"
      aria-atomic="true"
      data-bs-autohide="true"
    >
      <div class="toast-header">
        <strong class="me-auto">Pomyślnie dodano ćwiczenie</strong>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="toast"
          aria-label="Close"
        ></button>
      </div>
      <div class="toast-body">{{ message }}</div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <!-- Form for adding a new workout -->
  <form method="post">
    {% csrf_token %}

    <div class="row">
      <!-- Left column with exercise details -->
      <div class="col-md-6">
        <div class="row mb-3">
          <div class="form-group col-md-6">
            <label for="exercise">Rodzaj treningu:</label>
            <select name="exercise" id="exercise" class="form-control">
              <!-- Dropdown for selecting the type of exercise -->
              {% for exercise in exercises %}
              <option value="{{ exercise.id }}">{{ exercise.name }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="form-group col-md-6">
            <label for="created_at">Data i czas:</label>
            <input
              type="datetime-local"
              name="created_at"
              id="created_at"
              class="form-control"
              required
            />
          </div>
        </div>

        <div class="row mb-3">
          <div class="form-group col-md-6">
            <label for="duration">Czas trwania (minuty):</label>
            <input
              type="number"
              name="duration"
              id="duration"
              class="form-control"
              required
            />
          </div>

          <div class="form-group col-md-6">
            <label for="distance">Dystans (km):</label>
            <input
              type="text"
              name="distance"
              id="distance"
              class="form-control"
              required
              step="any"
            />
          </div>
        </div>
      </div>

      <!-- Right column with space for additional comments -->
      <div class="col-md-6">
        <div class="form-group h-100">
          <label for="comment">Notatka:</label>
          <textarea
            name="comment"
            id="comment"
            class="form-control h-100"
          ></textarea>
        </div>
      </div>
    </div>

    <!-- Submit button to add the exercise -->
    <button type="submit" class="btn btn-main">Dodaj ćwiczenie</button>
  </form>
</div>

{% endblock content %}

workout_app/workout_logs/templates/workout_logs/edit_workout.html
{% extends "workout_logs/layout.html" %}

{% block content %}

<div class="container">

  <!-- Page heading for editing a workout -->
  <h1>Edytuj trening</h1>

  <!-- Display success messages if any -->
  {% if messages %}
  <div id="toast-container" class="position-fixed top-0 end-0 p-3" style="z-index: 9999;">
    {% for message in messages %}
      <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
        <div class="toast-header">
          <strong class="me-auto">Pomyślnie edytowano trening</strong>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
          {{ message }}
        </div>
      </div>
    {% endfor %}
  </div>
  {% endif %}

  <!-- Form for editing an existing workout -->
  <form method="post">
  {% csrf_token %}
  
  <div class="row mb-3">
    <!-- Left column with exercise details -->
    <div class="col-md-6">
        <div class="form-group mb-3">
            <label for="exercise">Rodzaj treningu:</label>
            <select name="exercise" id="exercise" class="form-control">
                <!-- Dropdown for selecting the type of exercise -->
                {% for exercise in exercises %}
                    <option value="{{ exercise.id }}" {% if exercise.id == current_workout.exercise.id %}selected{% endif %}>
                        {{ exercise.name }}
                    </option>
                {% endfor %}
            </select>
        </div>

      <div class="form-group mb-3">
        <label for="created_at">Data i czas:</label>
        <!-- Input for selecting date and time -->
        <input type="datetime-local" name="created_at" id="created_at" class="form-control" value="{{ current_workout.created_at|date:'Y-m-d\TH:i' }}" required>
      </div>
      
      <div class="form-group mb-3">
        <label for="duration">Czas trwania (minuty):</label>
        <!-- Input for entering workout duration -->
        <input type="number" name="duration" id="duration" class="form-control" value="{{ duration_minutes }}" required step="1">
      </div>

      <div class="form-group mb-3">
        <label for="distance">Dystans (km):</label>
        <!-- Input for entering workout distance -->
        <input type="number" name="distance" id="distance" class="form-control" value="{{ current_workout.distance }}" required step="any">
      </div>
    </div>

    <!-- Right column with space for additional comments -->
    <div class="col-md-6">
      <div class="form-group h-100">
        <label for="comment">Notatka:</label>
        <!-- Textarea for entering additional comments -->
        <textarea name="comment" id="comment" class="form-control h-100" rows="5">{{ current_workout.comment }}</textarea>
      </div>
    </div>
  </div>
  
  <!-- Submit button to save changes and cancel button to go back to history -->
  <button type="submit" class="btn btn-main">Zapisz zmiany</button>
  <a href="{% url 'history' %}" class="btn btn-main-secondary">Anuluj</a>
</form>

</div>

{% endblock content %}

workout_app/workout_logs/templates/workout_logs/faq.html
{% extends "workout_logs/layout.html" %} {% block content %}

<div class="container mt-5">
  <!-- Page heading for the FAQ section -->
  <h1 class="text-center">Workout App FAQ</h1>

  <!-- Accordion for FAQ items -->
  <div class="accordion accordion-flush mt-4" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseOne"
          aria-expanded="false"
          aria-controls="collapseOne"
        >
          Jakie korzyści przynosi regularne uprawianie sportu?
        </button>
      </h2>
      <div
        id="collapseOne"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Regularne ćwiczenia sportowe przynoszą wiele korzyści, m.in. poprawę
            kondycji fizycznej, redukcję stresu, utrzymanie zdrowej wagi oraz
            wzmocnienie układu odpornościowego.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseTwo"
          aria-expanded="false"
          aria-controls="collapseTwo"
        >
          Jak często powinienem wykonywać treningi cardio?
        </button>
      </h2>
      <div
        id="collapseTwo"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Częstotliwość treningów cardio zależy od celów i kondycji fizycznej.
            Ogólnie, zaleca się 3-5 sesji cardio w tygodniu, trwających co
            najmniej 30 minut.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseThree"
          aria-expanded="false"
          aria-controls="collapseThree"
        >
          Jakie ćwiczenia mogę wykonywać w domu bez sprzętu?
        </button>
      </h2>
      <div
        id="collapseThree"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Istnieje wiele ćwiczeń bez sprzętu, takich jak przysiady, pompki,
            plank, czy skakanka. Można także skorzystać z ćwiczeń na siłowni
            domowej.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseFour"
          aria-expanded="false"
          aria-controls="collapseFour"
        >
          Czy treningi siłowe są odpowiednie dla kobiet?
        </button>
      </h2>
      <div
        id="collapseFour"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Tak, treningi siłowe są świetnym sposobem na zwiększenie siły i
            poprawę sylwetki zarówno u kobiet, jak i mężczyzn. Mogą przyczynić
            się do lepszej kondycji oraz utrzymania zdrowej masy ciała.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseFive"
          aria-expanded="false"
          aria-controls="collapseFive"
        >
          Jakie ćwiczenia są najlepsze dla utraty wagi?
        </button>
      </h2>
      <div
        id="collapseFive"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Skuteczne ćwiczenia na utratę wagi obejmują treningi cardio,
            interwałowe, oraz treningi siłowe. Ważne jest także utrzymanie
            zdrowej diety.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseSix"
          aria-expanded="false"
          aria-controls="collapseSix"
        >
          Czy treningi online są skuteczne?
        </button>
      </h2>
      <div
        id="collapseSix"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Tak, treningi online mogą być bardzo skuteczne. Dostęp do
            różnorodnych programów, instrukcji wideo i wsparcia online
            umożliwiają skuteczną pracę nad kondycją w dowolnym miejscu i
            czasie.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseSeven"
          aria-expanded="false"
          aria-controls="collapseSeven"
        >
          Czy istnieją ćwiczenia dla początkujących?
        </button>
      </h2>
      <div
        id="collapseSeven"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Tak, istnieje wiele ćwiczeń dedykowanych początkującym, które
            pomagają zbudować siłę, wytrzymałość i poprawić technikę wykonywania
            ćwiczeń.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseEight"
          aria-expanded="false"
          aria-controls="collapseEight"
        >
          Jak unikać kontuzji podczas treningu?
        </button>
      </h2>
      <div
        id="collapseEight"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Aby unikać kontuzji, ważne jest rozgrzewanie przed treningiem,
            stosowanie prawidłowej techniki, stopniowe zwiększanie
            intensywności, oraz słuchanie sygnałów ciała.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseNine"
          aria-expanded="false"
          aria-controls="collapseNine"
        >
          Czy treningi interwałowe są skuteczne?
        </button>
      </h2>
      <div
        id="collapseNine"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Tak, treningi interwałowe są bardzo skuteczne, pozwalając na
            spalanie kalorii, poprawę kondycji tlenowej, oraz przyspieszenie
            metabolizmu.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseTen"
          aria-expanded="false"
          aria-controls="collapseTen"
        >
          Jakie znaczenie ma dieta w treningu?
        </button>
      </h2>
      <div
        id="collapseTen"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Dieta odgrywa kluczową rolę w osiąganiu celów treningowych. Właściwe
            nawyki żywieniowe wspierają budowę mięśni, regenerację oraz utratę
            wagi.
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseEleven"
          aria-expanded="false"
          aria-controls="collapseEleven"
        >
          Czy ćwiczenia stretchingowe są ważne?
        </button>
      </h2>
      <div
        id="collapseEleven"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <div class="answer">
            Tak, ćwiczenia stretchingowe są ważne dla utrzymania elastyczności
            mięśni, poprawy zakresu ruchu oraz zapobiegania kontuzjom.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

workout_app/workout_logs/templates/workout_logs/index.html
<!-- Extends the base layout template -->
{% extends "workout_logs/layout.html" %}

<!-- Content Block -->
{% block content %}
<div class="container mt-5">
  <!-- Title for Register Workout Section -->
  <h1 class="text-center">Zarejestruj trening!</h1>

  <!-- Subtitle for Latest Exercises Section -->
  <h3 class="mt-4">Ostatnie ćwiczenia:</h3>

  <!-- Table Displaying Latest Exercises -->
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <!-- Table Header Row -->
        <tr>
          <th>Data</th>
          <th>Nazwa</th>
          <th>Czas trwania</th>
          <th>Dystans</th>
          <th style="width: 20%">Komentarz</th>
        </tr>
      </thead>
      <tbody>
        <!-- Loop through latest exercises and display in table rows -->
        {% for exercise in latest_exercises %}
        <tr>
          <td>{{ exercise.created_at|date:"Y-m-d" }}</td>
          <td>{{ exercise.exercise }}</td>
          <td>{{ exercise.duration }}</td>
          <td>{{ exercise.distance }} km</td>
          <td>{{ exercise.comment }}</td>
        </tr>
        {% empty %}
        <!-- Displayed when no exercises are found -->
        <tr>
          <td colspan="5">Nie znaleziono zarejestrowanych ćwiczeń.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- End of Content Block -->
{% endblock content %}

workout_app/workout_logs/templates/workout_logs/profile.html
{% extends "workout_logs/layout.html" %} {% block content %} {% load static %}

<!-- Container for User Profile Information -->
<div class="container">
  <div class="text-center">
    <!-- Displaying Flash Messages -->
    {% for message in messages %}
    <div
      class="alert {% if message.tags == 'success' %}alert-success{% elif message.tags == 'warning' %}alert-warning{% elif message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %}"
      role="alert"
    >
      {{ message }}
    </div>
    {% endfor %}

    <!-- Greeting Message with User's First and Last Name -->
    {% if request.user.first_name or request.user.last_name %}
    <h1>Witaj, {{ request.user.first_name }} {{ request.user.last_name }}</h1>
    {% endif %}

    <!-- Display Premium Account Information -->
    {% if is_premium_active %}
    <p>
      Konto Premium - do: {{ user_profile.premium_account.end_date|date:"d.m.Y"
      }} ({{ user_profile.premium_account.end_date|time:"H:i" }})
    </p>
    {% else %}
    <p>
      Nie masz premium? <a href="{% url 'process_payment' %}">Kup Premium</a>
    </p>
    {% endif %}

    <!-- Display User Information -->
    <ul>
      <ol>
        Nazwa użytkownika: {{ request.user.username }}
      </ol>
      <ol>
        Email: {{ request.user.email }}
      </ol>
    </ul>

    <!-- Display User Profile Picture -->
    <div {% if is_premium_active %}class="premium-avatar-animation" {% endif %}>
      {% if user_profile.profile_picture %}
      <img
        src="{{ user_profile.profile_picture.url }}"
        alt="Profile Picture"
        width="300"
        height="300"
        class="rounded-circle"
      />
      {% else %}
      <p>Domyślne zdjęcie profilowe</p>
      <img
        src="{% static 'images/default_profile_pic.png' %}"
        width="300"
        height="300"
        class="rounded-circle"
        alt="Zdjęcie domyślne"
      />
      {% endif %}
    </div>
  </div>

  <!-- Form for Updating User Profile Information -->
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <label for="first_name" class="form-label">Imię</label>
      <input
        type="text"
        name="first_name"
        id="first_name"
        class="form-control"
        value="{{ user.first_name }}"
      />
    </div>
    <div class="mb-3">
      <label for="last_name" class="form-label">Nazwisko</label>
      <input
        type="text"
        name="last_name"
        id="last_name"
        class="form-control"
        value="{{ user.last_name }}"
      />
    </div>
    <div class="mb-3">
      <label for="profile_picture" class="form-label">Zdjęcie profilowe</label>
      <input
        type="file"
        name="profile_picture"
        accept="image/*"
        id="id_profile_picture"
        class="form-control"
      />
    </div>
    <button type="submit" class="btn btn-main">Zapisz zmiany</button>
  </form>
</div>

{% endblock content %}